server:
  port: 8082

spring:
  application:
    name: resume-parser-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/resume_scannerDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: resume123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    cors:
      allowed-origins: 
        - "http://localhost:8080"
        - "http://localhost:8082"
        - "http://localhost:3000"
        - "http://localhost:3001"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - HEAD
      allowed-headers: "*"
      allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: resume-parser-service
  show-actuator: true

# File upload settings
app:
  file:
    upload-dir: ${APP_FILE_UPLOAD_DIR:uploads/resumes/}

file:
  upload:
    dir: uploads/resumes/
    max-size: 10MB

logging:
  level:
    com.resumescanner.resumeparser: ${LOG_LEVEL:DEBUG}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/resume-parser-service.log
