server:
  port: 8081

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/resume_scannerDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: user-management-service
  show-actuator: true

app:
  jwtSecret: ${JWT_SECRET:vQp7hP4tF9b6eVdnQXZ6kXdY9j3vE8v7nXf9yJw4kTzG1aK2sQq4pL4fF9b6eVdnQXZ6kXdY9j3vE8v7nXf9yJw4kTzG1aK2sQq4pL4f}
  jwtExpirationInMs: ${JWT_EXPIRATION:604800000}

logging:
  level:
    com.resumescanner.usermanagement: ${LOG_LEVEL:DEBUG}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-management-service.log
